### ISSUE TITLE
unserialize error in PHP 7.1

### ISSUE THREAD

**Issue by tidus2102** [yiisoft/yii#4137] opened 2017-02-11 03:27 UTC
Hi, I'm using Yii 1.1.17. Everything works with PHP 7.0.x. I upgrade to PHP 7.1 and got this issue:
> unserialize(): Unexpected end of serialized data

![error](https://cloud.githubusercontent.com/assets/7001637/22850844/bbaae902-f043-11e6-9537-20f4933daf3d.png)

Is there any way to fix this? Thanks.

**Comment by samdark** [comment] 2017-02-11 19:51
Try cleaning up runtime directory.

**Comment by tidus2102** [comment] 2017-02-12 05:42
Oh I cleared runtime directory and it works at first time load. But from second times, it got error again, look like CFileCache got problem in PHP 7.1. Should I use another cache component? I see we have many option [here](http://www.yiiframework.com/doc/guide/1.1/en/caching.overview). Thanks

**Comment by samdark** [comment] 2017-02-12 09:45
Yes. For now, switch to something else. Looks like a compatibility issue to fix...

**Comment by marcovtwout** [comment] 2017-02-15 13:40
Bug confirmed with latest yii master. Works on PHP 7.0.15, breaks on PHP 7.1.1

**Comment by marcovtwout** [comment] 2017-02-15 13:49
You can reproduce this error like this:

- Create a new webapp using yiic in yii-master
- Add in config/main.php
```
'cache'=>array(
    'class'=>'CFileCache',
),
'urlManager'=>array(
    'urlFormat'=>'path',
    'rules'=>array(
        'a'=>'b',
    ),
),
```
- Reload index page twice.

Will investigate a bit further.

**Comment by marcovtwout** [comment] 2017-02-15 13:56
My bad, this issue is already fixed in master (CFileCache, getValue(), file_get_contents() offset). See: https://github.com/yiisoft/yii/commit/e1eb6ef9a68eebe44dedfa2db7d2dc6ba595cc2b

**Comment by samdark** [comment] 2017-02-15 13:58
@tidus2102 can you check your issue with code from master?

**Comment by marcovtwout** [comment] 2017-02-15 14:11
I can tell from his stack trace his issue should be fixed in master. (see #0 it tries to unserialize "}", which corresponds to the -1 offset)

**Comment by samdark** [comment] 2017-02-15 15:52
@marcovtwout thanks for checking.

**Closed** 2017-02-15 15:52 UTC
Labels: compatibility:PHP7

**Comment by tidus2102** [comment] 2017-02-16 05:31
@samdark @marcovtwout Oh it works with master code. Sorry I didn't check the changelog first. Thanks so much!

**Comment by tom--** [comment] 2017-10-26 21:22
moved my app from php 7.0 to 7.1 and ran into this. upgrading yii from 1.1.14 to 1.1.19 fixed it

**Comment by Tarasovych** [comment] 2019-10-14 13:23
Same error with 2.0.15.1

**Comment by samdark** [comment] 2019-10-14 13:25
This is Yii 1.1 issue tracker. Please submit to https://github.com/yiisoft/yii2
