### ISSUE TITLE
Doc (EN / Definitive Guide) has unfixable typos

### ISSUE THREAD

**Issue by Bux666** [yiisoft/yii#1434] opened 2012-09-19 09:17 UTC
Some typos in The Definitive Guide to Yii documentation [EN] can't be fixed:
- There are several places in the document where instead of a apostrophe (single quote) the HTML code is placed (&#039 ;). **See page 11 for examples.**
- The used H4 (used as #### in the docs) is not converted. I thought they might be changed to ###, but I'm not sure that is expected. **See page 183 for an example: < h4 id="creating-x-4098x">Creating WidgetGenerator.php< /h4>**

Is there any way to fix this, let's say in the compile configuration of the PDF generation tool?

**Comment by samdark** [comment] 2016-11-09 22:59
Won't be fixed since 1.1 is reaching its EOL and the issue isn't significant.

**Closed by samdark** 2016-11-09 22:59 UTC
Labels: type:docs
