### ISSUE TITLE
"yii session object destruction failed" on PHP 5.6.12

### ISSUE THREAD

**Issue by alex-shamshurin** [yiisoft/yii#4059] opened 2016-06-24 12:34 UTC
User is not logged but I get that error.

PHP 5.6.12
 Windows 10.0 build 10586 (Windows 10)
Yii 1.1.18-dev

![session_yii_issue](https://cloud.githubusercontent.com/assets/1595209/16337775/9a92cfde-3a20-11e6-8efd-3a3ecd1189b9.jpg)

**Comment by samdark** [comment] 2016-06-24 14:38
How to reproduce it?

**Comment by salex772** [comment] 2016-06-24 15:08
I do not know, it's a big project, tell me what exactly you need to reproduce or I can show that via hangouts or skype.

This is a stacktrace:
```
#0 C:\OpenServer\domains\myproject\vendor\yiisoft\yii\framework\web\auth\CWebUser.php(233): WebUser->changeIdentity()
#1 C:\OpenServer\domains\myproject\protected\models\forms\FLoginForm.php(74): WebUser->login()
#2 C:\OpenServer\domains\myproject\protected\controllers\UserController.php(74): FLoginForm->login()
#3 C:\OpenServer\domains\myproject\vendor\yiisoft\yii\framework\web\actions\CInlineAction.php(49): UserController->actionLogin()
#4 C:\OpenServer\domains\myproject\vendor\yiisoft\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\OpenServer\domains\myproject\vendor\yiisoft\yii\framework\web\filters\CFilterChain.php(133): UserController->runAction()
#6 C:\OpenServer\domains\myproject\vendor\yiisoft\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\OpenServer\domains\myproject\vendor\yiisoft\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#8 C:\OpenServer\domains\myproject\vendor\yiisoft\yii\framework\web\filters\CInlineFilter.php(58): UserController->filterAccessControl()
#9 C:\OpenServer\domains\myproject\vendor\yiisoft\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#10 C:\OpenServer\domains\myproject\vendor\yiisoft\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\OpenServer\domains\myproject\vendor\yiisoft\yii\framework\web\CController.php(265): UserController->runActionWithFilters()
#12 C:\OpenServer\domains\myproject\vendor\yiisoft\yii\framework\web\CWebApplication.php(282): UserController->run()
#13 C:\OpenServer\domains\myproject\vendor\yiisoft\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#14 C:\OpenServer\domains\myproject\vendor\yiisoft\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\OpenServer\domains\myproject\index.php(53): CWebApplication->run()
REQUEST_URI=/login
in C:\OpenServer\domains\myproject\protected\models\forms\FLoginForm.php (74)
in C:\OpenServer\domains\myproject\protected\controllers\UserController.php (74)
in C:\OpenServer\domains\myproject\index.php (53)
```

**Comment by samdark** [comment] 2016-06-24 16:41
I have no idea how to reproduce it as well. Skype or hangouts won't help either since I need to know what is the problem exactly in order to fix it and cover it with a unit test.

**Comment by salex772** [comment] 2016-06-24 16:45
I will attach an example app later. First I need exclude all not related stuff.

**Comment by samdark** [comment] 2016-06-24 16:58
OK.

**Comment by samdark** [comment] 2016-11-09 23:03
Closing since no info was provided.

**Closed by samdark** 2016-11-09 23:03 UTC
