### ISSUE TITLE
remember login failed when share memcache session

### ISSUE THREAD

**Issue by vodcms** [yiisoft/yii#3811] opened 2015-03-21 06:54 UTC
mutli site share memcache session. remember is unvalid.

**Comment by samdark** [comment] 2015-03-21 06:57
Please provide details on how to reproduce it.

**Comment by vodcms** [comment] 2015-03-21 07:08
a website cofnig

        'user' => array(
            'autoRenewCookie' => true,
            'allowAutoLogin' => true,
            'stateKeyPrefix' => 'sso',
            'identityCookie' => array("domain" => '.abc.com')
        ),
        'cache' => array(
            'class' => 'CMemCache',
            'servers' => array(
                array(
                    'host' => '192.168.1.240',
                    'port' => 11211
                )
            ),
        ),
        'session' => array(
            'class' => 'CCacheHttpSession',
            'cacheID' => 'cache',
            'cookieParams' => array('path' => '/', 'domain' => '.abc.com'),
        ),

b website config

        'user' => array(
            'autoRenewCookie' => true,
            'allowAutoLogin' => true,
            'stateKeyPrefix' => 'sso',
            'identityCookie' => array("domain" => '.abc.com')
        ),
        'cache' => array(
            'class' => 'CMemCache',
            'servers' => array(
                array(
                    'host' => '192.168.1.240',
                    'port' => 11211
                )
            ),
        ),
        'session' => array(
            'class' => 'CCacheHttpSession',
            'cacheID' => 'cache',
            'cookieParams' => array('path' => '/', 'domain' => '.abc.com'),
        ),


 when i login remenber 

        $duration = $this->rememberMe ? 86400 * 30 : 86400; // 30 days
        Yii::app()->user->login($identity, $duration);


 but i last login app is not auto login  becase CSecurityManager validateData is false

**Comment by vodcms** [comment] 2015-03-21 07:22
because app read statebin path error.  must config
'statePersister' => array(
            'class' => 'CStatePersister',
            'stateFile' => '/tmp/state.bin'
        )

i think is a bug  app maybe diffrent os filesystem

**Comment by samdark** [comment] 2015-03-21 07:26
That's quite specific issue that occurs only in case of multiple websites using a single auth. That's no common for 1.1 so I don't think defaults should be changed.

**Comment by vodcms** [comment] 2015-03-21 07:29
yii supports the sharing of session, but because of the existence of this problem, leading to some functions can not be used, there should be necessary to make it work better

**Comment by samdark** [comment] 2015-03-21 07:35
Could be documented better.

**Comment by andyofb** [comment] 2015-05-11 19:07
What is the fix for this? I also am having issues with Remember me not working since I switched to Memcached

**Comment by samdark** [comment] 2015-05-11 19:15
Memcached is not a good choice for data you should not lose. It can clear not yet expired data w/o asking you in case of lack of resources. I'd try Redis.

**Comment by andyofb** [comment] 2015-05-11 19:18
I would have thought memcached is a good solution for session storage. I was referring to the following no longer working form me:
$duration = $this->rememberMe ? 86400 * 30 : 86400; // 30 days
    Yii::app()->user->login($identity, $duration);

**Comment by samdark** [comment] 2015-05-11 22:26
memcached is a wrong choice for sessions. Not really reliable. It's meant for data you can re-calculate and cache again in case of loss.

Remember me shouldn't have to do anything about memcached itself so most probably you're hitting memory limit or expiration or something like that and memcached erases your session data. Thus, there's nothing to restore and you're suddenly logged out.

**Closed** 2017-03-13 22:11 UTC
Labels: status:to be verified, type:docs, Won't Fix
