### ISSUE TITLE
Yii::getPathOfAlias should work with directories that have a 'dot'

### ISSUE THREAD

**Issue by pohnean** [yiisoft/yii#4058] opened 2016-06-24 09:05 UTC
Currently the Yii::getPathOfAlias function will simply translate any dots to DIRECTORY_SEPARATOR.

As a result, the path for folders with dot as a name is not translated correctly.
Example:
Yii::getPathOfAlias('node_modules.typeahead.js') becomes: 
<somepath>/node_modules/typeahead/js

Proposed solution:
Allow dots in aliases by escaping them:
Yii::getPathOfAlias('node_modules.typeahead\\.js')

**Comment by cebe** [comment] 2016-09-12 15:34
the problem is fixed in yii2, so we are not going to so anything about it in yii1 as it would break BC. Sorry.

**Closed by cebe** 2016-09-12 15:34 UTC

**Comment by georgezim85** [comment] 2019-06-14 21:48
Imagine that you need to publish an asset from a directory called "jquery.complexify" in "your_app/node_modules/"
There goes an example:

```
$baseUrl = Yii::app()->getAssetManager()->publish(Yii::getPathOfAlias('webroot.node_modules') . DIRECTORY_SEPARATOR . 'jquery.complexify');
$cs = Yii::app()->getClientScript();
$cs->registerScriptFile($baseUrl . DIRECTORY_SEPARATOR . 'jquery.complexify.js');
```
