### ISSUE TITLE
Gii PHP7 Deprecation: "Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP"

### ISSUE THREAD

**Issue by nacesprin** [yiisoft/yii#4090] opened 2016-09-17 08:34 UTC
Hello. When using Gii on PHP7, throws this warning deprecation message:

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP.

Attached for more examples.
![gii-deprecated](https://cloud.githubusercontent.com/assets/295375/18607077/44660a42-7cc2-11e6-9f80-32c590e2b8f4.png)

**Comment by cebe** [comment] 2016-09-17 14:33
duplicate of #4033

**Closed by cebe** 2016-09-17 14:33 UTC
