### ISSUE TITLE
"CProfileLogRoute found a mismatching code block" error message lacks the most basic expected information

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii#4128] opened 2017-01-29 00:20 UTC
I'm getting this error which I now need to debug:
```
CProfileLogRoute found a mismatching code block "system.db.CDbCommand.query(
SELECT response FROM google_request_cache
WHERE url=:url
. Bound with :url='geocode/json?place_id=ChIJT533myXybk0RA_d5CcdLbIY&language=ca')". Make sure the calls to Yii::beginProfile() and Yii::endProfile() be properly nested.
```
(btw I'm pretty sure it's caused by a bug in Yii, because I'm not calling `beginProfile` or `endProfile` ever)

The most irritating thing is that this message lacks THE MOST OBVIOUS piece of information you'd expect from an error message of this kind, and the one you need the most: **mismatching with what??**

Is the block contained in the error message one found in a `beginProfile` or in an `endProfile` call? And if it is an `endProfile`, what was the last open `beginProfile` that it doesn't match?

**Comment by teo1978** [comment] 2017-01-29 00:24
Also, btw, it says:
> **CProfileLogRoute** found

and I don't have any `CProfileRoute` enabled. The code printing the error seems to be in `CLogger`. So, saying *CProfileRoute found whatever* is quite misleading.

**Comment by cebe** [comment] 2017-01-29 20:09
do you have a stack trace of the error?

**Comment by cebe** [comment] 2017-01-29 20:12
The error message is thrown in the following two places:

- https://github.com/yiisoft/yii/blob/b2664930dd7a3394d4ffa4d03b7d78e3fa771af4/framework/logging/CProfileLogRoute.php#L120
- https://github.com/yiisoft/yii/blob/b2664930dd7a3394d4ffa4d03b7d78e3fa771af4/framework/logging/CLogger.php#L318

**Comment by teo1978** [comment] 2017-01-29 20:35
This was thrown from CLogger. I didn't save the stack trace, sorry

**Comment by samdark** [comment] 2017-02-02 13:44
Any idea on how to reproduce that?

**Comment by teo1978** [comment] 2017-02-02 14:06
Note that this report is about the lack of information in the error message, not about the fact that the error shouldn't be thrown in the first place (I would love to report that as a separate issue but I need to investigate it a little more).

So, to reproduce it you simply need to make some mismatching calls to `beginProfile` and `endProfile`, which should be pretty trivial. Also you shouldn't even need to reproduce the issue to see it.

To expand a little bit on what the issue is (which should be obvious): 
if you have some calls like this:
```
  beginProfile('xxx');
  //...
  beginProfile('yyy');
  //...
  endProfile('xxx'); // triggers the error
```
or like this:
```
  beginProfile('www');
  //...
  endProfile('zzz'); // triggers the error
```

What I expect is the error message to contain information about the call to `endProfile` triggering the error **AND** the call to `beginProfile` that was expected to be matched and isn't (in the first example `beginProfile('yyy')`, in the second `beginProfile('www')`.

This is the only way  one can debug an error like this.

**Comment by samdark** [comment] 2017-02-02 14:58
Overall agree. Also I don't see straightforward way to fix it so if you know how to do it, feel free to make a pull request. If not, I'll close the issue since our priority now is 2.0 and 1.1 issues accepted/fixed are mainly security and PHP 7 compatibility.

**Closed** 2017-03-13 22:17 UTC
Labels: Won't Fix
