### ISSUE TITLE
ActiveFinder case sensitivity issue on count.

### ISSUE THREAD

**Issue by twisted1919** [yiisoft/yii#3748] opened 2015-02-10 16:21 UTC
I use to write my queries by doing UPPER case for mysql keywords.

``` PHP
        $criteria = new CDbCriteria();
        $criteria->select = 'COUNT(DISTINCT(t.email)) as counter';
        $criteria->with = array(
            'list' => array(
                'select'   => false,
                'together' => true,
                'joinType' => 'INNER JOIN',
                'condition'=> 'list.customer_id = :cid',
                'params'   => array(':cid' => (int)$customer_id),
            ),
        );
        $criteria->addNotInCondition('list.status', array(Lists::STATUS_PENDING_DELETE));
        $subscribers = Yii::app()->format->formatNumber(ListSubscriber::model()->count($criteria));
```

And this produces a query like 

``` sql
SELECT COUNT(DISTINCT `t`.`subscriber_id`) FROM `mw_list_subscriber` `t`  INNER JOIN `mw_list` `list` ON (`t`.`list_id`=`list`.`list_id`) WHERE ((list.status!=:ycp3)) AND (list.customer_id = :cid)
```

Which is by far what i need to be (Please note that i intentionally avoid group by here).  
And this is is because the regex at https://github.com/yiisoft/yii/blob/1.1.16/framework/db/ar/CActiveFinder.php#L750 checks only for lowecase letters. If i change the $criteria->select to lowercase letters, then all is good.

On the other hand, when there's no need for join, CDbCommandBuilder does a case insensitive lookup with stripos: https://github.com/yiisoft/yii/blob/1.1.16/framework/db/schema/CDbCommandBuilder.php#L132  

I wonder how was this overlooked for so long...

**Comment by nineinchnick** [comment] 2015-02-10 20:57
This might be a duplicate of #3696. The line mentioned in CDbCommandBuilder may suffer from the same bug as in #268, that is it should check if the line starts with `count(`, not only `count` which may be a part of a column name, like `country`.

**Closed** 2017-03-13 22:11 UTC
Labels: status:to be verified, type:bug, Won't Fix
