### ISSUE TITLE
Anchor tags are sometimes self closed, which results in invalid html

### ISSUE THREAD

**Issue by My6UoT9** [yiisoft/yii#4091] opened 2016-09-21 11:56 UTC
The function CHtml::link does not force the tag to be closed. When $content is false, the tag gets self closed.
So you might get something like 
`<a href=".."/> `
instead of 
`<a href=".."></a>`

In any case it is valid xhtml, but invalid html. And for example IE9 does not handle it correctly.

**Comment by cebe** [comment] 2016-09-22 13:26
isn't an empty link also invalid HTML? it would not be displayed, so why do you want to do that?

**Comment by My6UoT9** [comment] 2016-09-22 14:22
First off, sorry for not having time to setup a test case. I might have time next week.
It was actually Yii itself which generated such a link, it happens in combination with CLinkPager->createPageButton(...).
When in the pager configuration this is done:
```
....
'pager' => [
                        'prevPageLabel' => '<i class="fa fa-angle-left"></i>',
                        'firstPageLabel' => false, //'<i class="fa fa-angle-double-left"></i>',
                        'nextPageLabel' => '<i class="fa fa-angle-right"></i>',
                        'lastPageLabel' => false,
....
```

Then the $content is set to false. Well again sorry, I am not 100% sure about this. I was debugging this problem yesterday, and tracked it down to CHtml::link; where I simply add a conditional to set $text to an empty string if is false. And then it finally worked.
Else IE9 simply took the next available closing anchor tag '</a>' and mangled everything between that into the link.

**Comment by rob006** [comment] 2016-09-22 16:35
> isn't an empty link also invalid HTML? it would not be displayed, so why do you want to do that?

You can make it visible by CSS, so the content of the link is not needed.

**Comment by My6UoT9** [comment] 2016-09-27 13:39
I tried to reproduce the issue with a clean Yii, so I took the demo "Post" and tried recreating the issue.
It worked fine, must be something on my end, which cause pagelabels with false to be outputted despite being set to false. But I did not have much time for this, I mean am not sure there is no problem.. 
hehe sorry.

I would still suggest to force properly closed anchor tags through CHtml, as it can be very difficult to diagnose.

**Comment by samdark** [comment] 2016-09-28 09:26
Since there's no good way to reproduce it I'll close the issue.

**Closed by samdark** 2016-09-28 09:26 UTC

**Comment by My6UoT9** [comment] 2016-09-28 09:42
Well it is simple to reproduce.
http://www.yiiframework.com/doc/api/1.1/CHtml#link-detail
`CHtml::link(false, 'http://myurl', ['class'=>'myclass']);`

That will create a self closed anchor tag, which is invalid HTML - but valid XHTML.

**Comment by cebe** [comment] 2016-09-28 12:35
1. Passing an empty string to CHtml::link() will produce `<a ...></a>` as expected, passing false will create a self closing tag. that is expected behavior of `CHtml::tag()`.
2. setting `'lastPageLabel' => false,` in CLinkPager should [not render a button at all](https://github.com/yiisoft/yii/blob/04f97932ddfbf9c5bdaae0a6a41b851544704a27/framework/web/widgets/pagers/CLinkPager.php#L179) so I guess it is something in your code that causes this behavior.
